version: 2.1

orbs:
  cypress: cypress-io/cypress@1

executors:
  default:
    working_directory: ~/project/dimigoin-front
    docker:
      - image: circleci/node:latest

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - dimigoin-front
  build:
    executor: default
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dimigoin-front
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn run deploy

workflows:
  test-and-deploy:
    jobs:
      - install
      - cypress/run:
          name: test
          yarn: true
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - cypress/run
            - build
