version: 2.1

executors:
  default:
    working_directory: ~/project/dimigoin-front
    docker:
      - image: circleci/node:latest

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - dimigoin
  build:
    executor: default
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn build
  test-e2e:
    executor: default
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn deploy

workflows:
  test-and-deploy:
    jobs:
      - install
      - test-e2e:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test-e2e
            - build
