export const REGISTER = 'ACCOUNT:REGISTER'
export const VERIFY = 'ACCOUNT:VERIFY'

export const LOGIN = 'ACCOUNT:LOGIN_SUCCESS'
export const LOGOUT = 'ACCOUNT:LOGOUT'

export const UPDATE_NOTIFICATIONS = 'ACCOUNT:UPDATE_NOTIFICATIONS'

export const UPDATE_INFO = 'ACCOUNT:UPDATE_INFO'
