export const LOGIN_SUCCESS = 'ACCOUNT:LOGIN_SUCCESS'
export const LOGOUT = 'ACCOUNT:LOGOUT'

export const UPDATE_NOTIFICATIONS = 'ACCOUNT:UPDATE_NOTIFICATIONS'

export const UPDATE_INFO = 'ACCOUNT:UPDATE_INFO'
