export const NAMESPACE = 'account'

export const REMOVE_TOKENS = `${NAMESPACE}:LOGOUT`
export const ASSIGN_ACCESS_TOKEN = `${NAMESPACE}:ASSIGN_ACCESS_TOKEN`
export const ASSIGN_REFRESH_TOKEN = `${NAMESPACE}:ASSIGN_REFRESH_TOKEN`

export const UPDATE_INFO = `${NAMESPACE}:UPDATE_INFO`
export const RESET_INFO = `${NAMESPACE}:RESET_INFO`
