export { register, getAccessToken, verifyStudent } from './auth'
export * as meal from './meal'
export * as service from './service'
export { default as axios } from './axios'
export * as circle from './circle'
export * as afterschool from './afterschool'
export * as ingang from './ingang'
export * as assignment from './assignment'
export * as dets from './dets'
