export { default as auth } from './auth'
export { default as request } from './wrapper'
export { default as teacher } from './teacher'
export { default as management } from './management'
export { default as assignment } from './assignment'
